# Generated by Django 6.0.2 on 2026-02-24 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_mime_type',
            field=models.CharField(blank=True, default='image/jpeg', help_text='MIME type of the stored cover image.', max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
