# Generated by Django 6.0.2 on 2026-02-24 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_cover_mime_type_alter_book_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_id',
            field=models.CharField(blank=True, editable=False, help_text='Auto-generated. Format: <PREFIX><NNN> e.g. DOO001', max_length=20, unique=True, verbose_name='Book ID'),
        ),
    ]
