# Generated by Django 6.0.2 on 2026-02-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='photo_mime',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='staff',
            name='photo',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
