# Generated by Django 6.0.2 on 2026-02-25 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_staff_photo_mime_alter_staff_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('librarian', 'Librarian'), ('assistant', 'Library Assistant')], default='librarian', max_length=20),
        ),
    ]
