# Generated by Django 6.0.2 on 2026-02-25 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_staff_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='is_staff_user',
            field=models.BooleanField(default=True, help_text='1 = can log in to staff dashboard  |  0 = access revoked.', verbose_name='Portal Access'),
        ),
        migrations.AddField(
            model_name='staff',
            name='owner',
            field=models.ForeignKey(default=1, help_text='The superuser/admin who created this staff member.', on_delete=django.db.models.deletion.CASCADE, related_name='owned_staff', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
