# Generated by Django 6.0.2 on 2026-02-23 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='library_logo_mime',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='library',
            name='library_logo',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
