# Generated by Django 6.0.2 on 2026-02-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membersettings',
            name='student_borrow_limit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='membersettings',
            name='teacher_borrow_limit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
