# Generated by Django 6.0.2 on 2026-02-20 16:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='library',
            options={'ordering': ['-created_at'], 'verbose_name': 'Library', 'verbose_name_plural': 'Libraries'},
        ),
        migrations.AddField(
            model_name='library',
            name='institute_type',
            field=models.CharField(choices=[('private', 'Institution'), ('government_rural', 'Government – Rural'), ('government_urban', 'Government – Urban')], default='private', max_length=50),
        ),
        migrations.AddField(
            model_name='library',
            name='library_code',
            field=models.CharField(blank=True, db_index=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='library',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='library',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='library',
            name='allotted_books',
            field=models.PositiveIntegerField(help_text='Max books per member', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='library',
            name='borrowing_period',
            field=models.PositiveIntegerField(help_text='Borrowing period in days', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)]),
        ),
        migrations.AlterField(
            model_name='library',
            name='institute_email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='library',
            name='late_fine',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='library',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='library', to=settings.AUTH_USER_MODEL),
        ),
    ]
