# Generated by Django 6.0.2 on 2026-02-21 15:46

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_library_options_library_institute_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='library',
            options={},
        ),
        migrations.RemoveField(
            model_name='library',
            name='allotted_books',
        ),
        migrations.RemoveField(
            model_name='library',
            name='borrowing_period',
        ),
        migrations.RemoveField(
            model_name='library',
            name='late_fine',
        ),
        migrations.AddField(
            model_name='library',
            name='library_logo',
            field=models.ImageField(blank=True, null=True, upload_to='library_logos/'),
        ),
        migrations.AlterField(
            model_name='library',
            name='institute_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='library',
            name='institute_type',
            field=models.CharField(choices=[('private', 'Private Institution'), ('government_rural', 'Government – Rural'), ('government_urban', 'Government – Urban')], default='private', max_length=50),
        ),
        migrations.CreateModel(
            name='AppearanceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dark_mode', models.BooleanField(default=False)),
                ('compact_view', models.BooleanField(default=False)),
                ('dashboard_animation', models.BooleanField(default=True)),
                ('show_welcome_message', models.BooleanField(default=True)),
                ('primary_color', models.CharField(default='#2563eb', max_length=20)),
                ('library', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appearance', to='accounts.library')),
            ],
        ),
        migrations.CreateModel(
            name='LibraryRuleSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('late_fine', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('borrowing_period', models.PositiveIntegerField(default=14, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)])),
                ('max_books_per_member', models.PositiveIntegerField(default=3)),
                ('max_renewal_count', models.PositiveIntegerField(default=1)),
                ('grace_period', models.PositiveIntegerField(default=0)),
                ('lost_book_charge_formula', models.CharField(blank=True, max_length=255, null=True)),
                ('auto_fine', models.BooleanField(default=True)),
                ('allow_renewal', models.BooleanField(default=True)),
                ('allow_partial_payment', models.BooleanField(default=False)),
                ('auto_mark_lost', models.BooleanField(default=False)),
                ('allow_advance_booking', models.BooleanField(default=False)),
                ('library', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='accounts.library')),
            ],
        ),
        migrations.CreateModel(
            name='MemberSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_borrow_limit', models.PositiveIntegerField(default=3)),
                ('teacher_borrow_limit', models.PositiveIntegerField(default=5)),
                ('membership_validity_days', models.PositiveIntegerField(default=365)),
                ('member_id_format', models.CharField(default='MEM-{0001}', max_length=50)),
                ('allow_self_registration', models.BooleanField(default=False)),
                ('require_admin_approval', models.BooleanField(default=True)),
                ('enable_member_id_download', models.BooleanField(default=True)),
                ('allow_profile_edit', models.BooleanField(default=True)),
                ('library', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_settings', to='accounts.library')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_overdue_reminder', models.BooleanField(default=True)),
                ('sms_reminder', models.BooleanField(default=False)),
                ('monthly_usage_report', models.BooleanField(default=True)),
                ('weekly_database_backup', models.BooleanField(default=True)),
                ('daily_activity_summary', models.BooleanField(default=False)),
                ('library', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.library')),
            ],
        ),
        migrations.CreateModel(
            name='SecuritySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('two_factor_auth', models.BooleanField(default=False)),
                ('lock_after_failed_attempts', models.BooleanField(default=True)),
                ('force_password_reset', models.BooleanField(default=False)),
                ('login_email_notification', models.BooleanField(default=True)),
                ('allow_multiple_device_login', models.BooleanField(default=True)),
                ('failed_login_attempts_limit', models.PositiveIntegerField(default=5)),
                ('library', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security', to='accounts.library')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('basic', 'Basic'), ('silver', 'Silver'), ('gold', 'Gold'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='basic', max_length=20)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('library', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='accounts.library')),
            ],
        ),
    ]
