# Generated by Django 6.0.2 on 2026-02-22 06:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_library_options_remove_library_allotted_books_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='library',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='libraryrulesettings',
            name='max_books_per_member',
            field=models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='securitysettings',
            name='failed_login_attempts_limit',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
