# Generated by Django 6.0.2 on 2026-03-06 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='book_copy',
            field=models.ForeignKey(blank=True, help_text='The specific copy that was issued.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='books.bookcopy'),
        ),
    ]
