# Generated by Django 6.0.2 on 2026-02-25 17:31

import django.core.validators
import django.db.models.deletion
import members.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='academic_notes',
            field=models.TextField(blank=True, help_text='Additional academic remarks or notes.', null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='specialization',
            field=models.CharField(blank=True, help_text='Specialization or elective subject (optional).', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='book_accession_number',
            field=models.CharField(blank=True, help_text='Library accession / barcode number of the physical copy.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='fine_paid_date',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the fine was paid.', null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(help_text='Short course code (e.g. BTECH, MBA).', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.PositiveSmallIntegerField(default=3, help_text='Duration of the course in years.'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(help_text='Full course name.', max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='owner',
            field=models.ForeignKey(help_text='Library admin who owns this record.', on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(help_text='Short department code (e.g. CSE, MBA).', max_length=20),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(help_text='Full department name.', max_length=200),
        ),
        migrations.AlterField(
            model_name='department',
            name='owner',
            field=models.ForeignKey(help_text='Library admin who owns this record.', on_delete=django.db.models.deletion.CASCADE, related_name='departments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='member',
            name='admission_year',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Year of admission (e.g. 2022).', null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='alternate_phone',
            field=models.CharField(blank=True, help_text='Optional alternate 10-digit number.', max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits.', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='member',
            name='clearance_date',
            field=models.DateTimeField(blank=True, help_text='Timestamp when clearance was granted.', null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='clearance_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('cleared', 'Cleared')], default='pending', help_text='Library clearance status (all books returned, dues cleared).', max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='cleared_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who granted clearance.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleared_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='member',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the member record was created.'),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(help_text='Must be unique per owner.', max_length=254),
        ),
        migrations.AlterField(
            model_name='member',
            name='guardian_phone',
            field=models.CharField(blank=True, help_text='Parent/guardian 10-digit number.', max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits.', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='member',
            name='inactive_reason',
            field=models.TextField(blank=True, help_text='Reason for marking the member inactive.', null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='inactive_since',
            field=models.DateTimeField(blank=True, help_text="Automatically set when status changes to 'inactive'.", null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_id',
            field=models.CharField(help_text='Unique member ID per owner. Auto-generated if left blank.', max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='owner',
            field=models.ForeignKey(help_text='Library admin who owns this member record.', on_delete=django.db.models.deletion.CASCADE, related_name='members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(help_text='10-digit mobile number.', max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits.', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='member',
            name='photo',
            field=models.ImageField(blank=True, help_text='Member passport photo. Stored as a file on disk; DB column holds the file path only.', null=True, upload_to=members.models._photo_upload_path),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='book_isbn',
            field=models.CharField(blank=True, help_text='ISBN-10 or ISBN-13.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='due_date',
            field=models.DateField(help_text='Date by which the book must be returned.'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='fine_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Fine amount in local currency.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='fine_paid',
            field=models.BooleanField(default=False, help_text='True once the fine has been collected.'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='issue_date',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the book was issued.'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='issue_notes',
            field=models.TextField(blank=True, help_text='Condition of the book at the time of issue, etc.', null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='issued_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who issued the book.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='owner',
            field=models.ForeignKey(help_text='Library admin who owns this transaction.', on_delete=django.db.models.deletion.CASCADE, related_name='member_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='return_date',
            field=models.DateTimeField(blank=True, help_text="Actual return timestamp. Auto-set on save when status = 'returned'.", null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='return_notes',
            field=models.TextField(blank=True, help_text='Condition of the book at the time of return, damage notes, etc.', null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='returned_to',
            field=models.ForeignKey(blank=True, help_text='Staff member who received the returned book.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display label, e.g. "1st Year", "Final Year".', max_length=100)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Sort order — lower value appears first.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(help_text='Library admin who owns this record.', on_delete=django.db.models.deletion.CASCADE, related_name='academic_years', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Academic Year',
                'verbose_name_plural': 'Academic Years',
                'ordering': ['order', 'name'],
                'unique_together': {('owner', 'name')},
            },
        ),
        migrations.AlterField(
            model_name='member',
            name='year',
            field=models.ForeignKey(blank=True, help_text='Academic year (e.g. "1st Year", "Final Year").', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='members.academicyear'),
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display label, e.g. "Semester 1", "Spring 2025".', max_length=100)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Sort order — lower value appears first.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(help_text='Library admin who owns this record.', on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Semester',
                'verbose_name_plural': 'Semesters',
                'ordering': ['order', 'name'],
                'unique_together': {('owner', 'name')},
            },
        ),
        migrations.AddField(
            model_name='member',
            name='semester',
            field=models.ForeignKey(blank=True, help_text='Current semester (e.g. "Semester 3").', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='members.semester'),
        ),
    ]
